/**
 * People example
 * The people API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Car } from './car';


export interface Person { 
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    gender: Person.GenderEnum;
    birthDate: string;
    car: Car;
}
export namespace Person {
    export type GenderEnum = 'male' | 'female';
    export const GenderEnum = {
        Male: 'male' as GenderEnum,
        Female: 'female' as GenderEnum
    };
}


