/**
 * People example
 * The people API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Car } from './car';
import { Gender } from './gender';


export interface Person { 
    gender: Gender;
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    birthDate: string;
    car: Car;
}

